'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { HEADER_LOGO } from './brand';
import { loadCatalog, money, winePath } from './catalogLoader';

function CartIcon(){return <svg viewBox="0 0 24 24"><circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l2.4 10.4a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 2-1.6L21 8H7"/></svg>}
function SearchIcon(){return <svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>}
function MenuIcon(){return <svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>}
function CloseIcon(){return <svg viewBox="0 0 24 24"><path d="M5 5l14 14M19 5L5 19"/></svg>}
function Arrow(){return <span aria-hidden="true">→</span>}
function InstagramIcon(){return <svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>}
function WhatsIcon(){return <img className="social-icon-img" src="https://cdn.simpleicons.org/whatsapp/ffffff" alt="" draggable="false"/>}
function Flag({code,name,className=''}){return code?<span className={`flag-wrap ${className}`} title={name}><img src={`https://flagcdn.com/w80/${code}.png`} alt={`Bandeira de ${name}`} draggable="false"/></span>:null}
function Bottle({wine}){return <div className="bottle-wrap"><div className={`bottle ${wine?.tone||'blend'}`}><div className="neck"/><div className="shoulder"/><div className="body"><div className="label"><b>{(wine?.name||'VINHO').slice(0,18)}</b><small>{(wine?.winery||'VIDEIRA').slice(0,18)}</small></div></div></div></div>}
function ProductVisual({wine}){return wine?.image_url?<img className="wine-photo" src={wine.image_url} alt={wine.name} draggable="false"/>:<Bottle wine={wine}/>} 
function DragSlider({children,className=''}){const ref=useRef(null);const st=useRef({down:false,x:0,left:0,drag:false});const down=e=>{if(e.pointerType!=='mouse'||e.button!==0)return;const el=ref.current;if(!el)return;st.current={down:true,x:e.clientX,left:el.scrollLeft,drag:false}};const move=e=>{const el=ref.current;if(!el||!st.current.down||e.pointerType!=='mouse')return;const dx=e.clientX-st.current.x;if(!st.current.drag&&Math.abs(dx)>8){st.current.drag=true;el.classList.add('dragging');try{el.setPointerCapture?.(e.pointerId)}catch{}}if(st.current.drag){e.preventDefault();el.scrollLeft=st.current.left-dx}};const end=e=>{const el=ref.current;if(!el)return;st.current.down=false;el.classList.remove('dragging');if(st.current.drag){try{el.releasePointerCapture?.(e.pointerId)}catch{}}};const click=e=>{if(st.current.drag){e.preventDefault();e.stopPropagation();st.current.drag=false}};return <div ref={ref} className={`horizontal-scroll drag-slider ${className}`} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onClickCapture={click}>{children}</div>}
function ProductCard({w,onAdd}){return <article className="wine-card"><Flag code={w.flag} name={w.country} className="origin-flag"/><a className="wine-card-link" href={winePath(w)}><div className="wine-image"><ProductVisual wine={w}/></div><div className="wine-meta"><small>{w.country||'Vinho'}</small><h3>{w.name}</h3><p>{w.winery}</p><span>{w.grapeDisplay||w.type||''}</span></div></a><div className="price-line"><strong>{money(w.price)}</strong><button onClick={e=>{e.preventDefault();e.stopPropagation();onAdd(w)}} aria-label={`Adicionar ${w.name}`}><CartIcon/></button></div></article>}

export default function Page(){
 const [wines,setWines]=useState([]),[cart,setCart]=useState([]),[cartOpen,setCartOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{loadCatalog().then(setWines).catch(console.error)},[]);
 const total=useMemo(()=>cart.reduce((s,p)=>s+Number(p.price||0),0),[cart]);
 const add=p=>setCart(v=>[...v,p]); const remove=i=>setCart(v=>v.filter((_,x)=>x!==i));
 const checkout=()=>{const lines=cart.map(p=>`• ${p.name} — ${money(p.price)}`).join('\n');window.open(`https://wa.me/5545999056277?text=${encodeURIComponent(`Olá! Quero consultar estes vinhos da Videira Vinhoteca:\n\n${lines}\n\nTotal: ${money(total)}`)}`,'_blank','noopener,noreferrer')};
 const doSearch=()=>{if(!searchOpen){setSearchOpen(true);return}if(query.trim())location.href=`/loja?q=${encodeURIComponent(query.trim())}`};
 const countries=useMemo(()=>{const order=['Brasil','Argentina','Chile','França','Itália','Espanha','Portugal','África do Sul','Uruguai','Estados Unidos','Alemanha'];const map=new Map();wines.forEach(w=>w.country&&map.set(w.country,w.flag));return [...map].sort((a,b)=>{const ia=order.indexOf(a[0]),ib=order.indexOf(b[0]);return (ia<0?99:ia)-(ib<0?99:ib)}).slice(0,10)},[wines]);
 const grapes=useMemo(()=>{const pref=['Malbec','Cabernet Sauvignon','Chardonnay','Sauvignon Blanc','Pinot Noir','Merlot','Carménère','Sangiovese','Tannat','Syrah','Blends'];return pref.filter(g=>wines.some(w=>w.filterGrape===g)).slice(0,9)},[wines]);
 const wineries=useMemo(()=>{const m={};wines.forEach(w=>{if(w.winery)m[w.winery]=(m[w.winery]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,8)},[wines]);
 const featured=wines.slice(0,10), newOnes=wines.slice(-10).reverse(), malbecs=wines.filter(w=>w.filterGrape==='Malbec').slice(0,10);

 return <>
  <header className="floating-header"><div className="header-pill"><a className="header-logo" href="#inicio"><img src={HEADER_LOGO} alt="Videira Vinhoteca"/></a><nav><a className="active" href="#inicio">Início</a><a href="#vinhos">Vinhos</a><a href="#uvas">Uvas</a><a href="#bodegas">Bodegas</a><a href="#sobre">Sobre nós</a><a href="#faq">FAQ</a></nav><div className="header-actions"><div className={`header-search ${searchOpen?'open':''}`}>{searchOpen&&<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doSearch()} placeholder="Buscar vinho..."/>}<button className="icon-btn search-btn" onClick={doSearch}><SearchIcon/></button></div><button className="icon-btn cart-icon" onClick={()=>setCartOpen(true)}><CartIcon/>{cart.length>0&&<span>{cart.length}</span>}</button><a className="shop-pill" href="/loja">Loja <Arrow/></a><button className={`icon-btn mobile-menu-btn ${menuOpen?'is-open':''}`} onClick={()=>setMenuOpen(v=>!v)} aria-label={menuOpen?'Fechar menu':'Abrir menu'}>{menuOpen?<CloseIcon/>:<MenuIcon/>}</button></div></div></header>
  <main>
   <section id="inicio" className="hero-clean hero-text-only"><div className="hero-text"><p className="kicker">CURADORIA DE VINHOS</p><h1>Grandes vinhos,<br/>bons momentos.</h1><p>Uma seleção de rótulos nacionais e importados para descobrir novas histórias em cada taça.</p><a className="primary-btn" href="/loja">Ver catálogo <Arrow/></a></div></section>
   <section className="regions-strip section-shell"><div className="slider-head"><h2>Explore por país</h2><a href="/loja">Ver todos <Arrow/></a></div><DragSlider className="compact">{countries.map(([name,flag],i)=><a href={`/loja?pais=${encodeURIComponent(name)}`} className={`region-card region-${i+1}`} key={name}><Flag code={flag} name={name} className="country-flag"/><div><strong>{name}</strong><span>Ver rótulos do país</span></div><Arrow/></a>)}</DragSlider></section>
   <section id="vinhos" className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">NOSSA SELEÇÃO</p><h2>Vinhos em destaque</h2></div><a href="/loja">Ver todos <Arrow/></a></div><DragSlider className="product-row">{featured.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>
   <section className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">CATÁLOGO 2026</p><h2>Últimos adicionados</h2></div><a href="/loja">Ver todos <Arrow/></a></div><DragSlider className="product-row">{newOnes.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>
   <section className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">UMA UVA, MUITOS ESTILOS</p><h2>Malbecs</h2></div><a href="/loja?uva=Malbec">Ver todos <Arrow/></a></div><DragSlider className="product-row">{malbecs.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>
   <section id="uvas" className="section-shell"><div className="slider-head"><div><p className="kicker dark">DESCUBRA SEU ESTILO</p><h2>Por uva</h2></div><a href="/loja">Ver todas <Arrow/></a></div><DragSlider className="grape-row">{grapes.map((g,i)=><a href={`/loja?uva=${encodeURIComponent(g)}`} className={`grape-tile grape-${i+1}`} key={g}><div><strong>{g}</strong><span>{g==='Blends'?'Misturas de duas ou mais uvas':'Ver rótulos'}</span></div><Arrow/></a>)}</DragSlider></section>
   <section id="bodegas" className="section-shell"><div className="slider-head"><div><p className="kicker dark">PRODUTORES</p><h2>Bodegas em destaque</h2></div><a href="/loja">Ver todas <Arrow/></a></div><DragSlider className="winery-row">{wineries.map(([name,count],i)=><a href={`/loja?bodega=${encodeURIComponent(name)}`} className={`winery-card winery-${i+1}`} key={name}><div className="winery-logo-slot"><span>{name.split(' ').map(v=>v[0]).join('').slice(0,3)}</span></div><div><strong>{name}</strong><span>{count} rótulos</span></div><Arrow/></a>)}</DragSlider></section>
   <section id="sobre" className="section-shell about-section"><div className="slider-head"><div><p className="kicker dark">VIDEIRA VINHOTECA</p><h2>Sobre nós</h2></div></div><div className="about-card"><p>Selecionamos vinhos com identidade, boa procedência e histórias que merecem ser compartilhadas.</p></div></section>
   <section id="faq" className="section-shell faq-section"><div className="slider-head"><div><p className="kicker dark">DÚVIDAS FREQUENTES</p><h2>FAQ</h2></div></div><div className="faq-list"><details><summary>Como faço um pedido?</summary><p>Adicione os rótulos ao carrinho e clique em “Continuar no WhatsApp”.</p></details><details><summary>Posso filtrar os vinhos?</summary><p>Sim. Na Loja você pode pesquisar e filtrar por país, uva e bodega.</p></details><details><summary>Vocês entregam para outras cidades?</summary><p>Consulte disponibilidade, prazo e frete diretamente pelo WhatsApp.</p></details></div></section>
  </main>
  <footer><div className="footer-brand"><div className="footer-logo-lockup"><img src={HEADER_LOGO} alt="Videira Vinhoteca"/></div><p>Curadoria de vinhos com identidade.</p></div><div className="footer-columns"><div><h4>Menu</h4><a href="#inicio">Início</a><a href="/loja">Loja</a><a href="#uvas">Uvas</a><a href="#bodegas">Bodegas</a></div><div><h4>Políticas</h4><a href="/politicas/privacidade">Privacidade</a><a href="/politicas/trocas">Trocas e devoluções</a><a href="/politicas/termos">Termos de uso</a></div></div><div className="footer-contact"><h4>Redes sociais</h4><div className="socials"><a href="https://instagram.com/Videiravinhoteca" target="_blank"><InstagramIcon/></a><a href="https://wa.me/5545999056277" target="_blank"><WhatsIcon/></a></div><span>@Videiravinhoteca</span></div></footer><div className="site-bottom">© 2026 Videira Vinhoteca · CNPJ 69.423.008/0001-67</div>

  <aside className={`mobile-menu ${menuOpen?'open':''}`}>
    <div className="mobile-menu-shell">
      <nav className="mobile-menu-links"><a href="#inicio" onClick={()=>setMenuOpen(false)}>Início</a><a href="/loja">Loja</a><a href="#vinhos" onClick={()=>setMenuOpen(false)}>Vinhos</a><a href="#uvas" onClick={()=>setMenuOpen(false)}>Uvas</a><a href="#bodegas" onClick={()=>setMenuOpen(false)}>Bodegas</a><a href="#sobre" onClick={()=>setMenuOpen(false)}>Sobre nós</a><a href="#faq" onClick={()=>setMenuOpen(false)}>FAQ</a></nav>
    </div>
  </aside>{menuOpen&&<button className="menu-backdrop" onClick={()=>setMenuOpen(false)}/>}
  <a className="whatsapp-float" href="https://wa.me/5545999056277" target="_blank"><WhatsIcon/></a>
  <aside className={`cart-drawer ${cartOpen?'open':''}`}><button className="drawer-close" onClick={()=>setCartOpen(false)}>×</button><p className="kicker dark">SEU CARRINHO</p><h2>Minha seleção</h2><div className="cart-items">{cart.length===0?<p className="empty">Seu carrinho está vazio.</p>:cart.map((p,i)=><div className="cart-item" key={i}><div><strong>{p.name}</strong><span>{p.winery}</span></div><div><b>{money(p.price)}</b><button onClick={()=>remove(i)}>Remover</button></div></div>)}</div><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="checkout" disabled={!cart.length} onClick={checkout}>Continuar no WhatsApp</button></aside>{cartOpen&&<button className="backdrop" onClick={()=>setCartOpen(false)}/>}
 </>;
}
