'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { HEADER_LOGO } from './brand';
import { loadCatalog, loadWineries, money, winePath } from './catalogLoader';
import useCart from './useCart';
import WineThumb from './WineThumb';

function CartIcon(){return <svg viewBox="0 0 24 24"><circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l2.4 10.4a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 2-1.6L21 8H7"/></svg>}
function SearchIcon(){return <svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>}
function MenuIcon(){return <svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>}
function CloseIcon(){return <svg viewBox="0 0 24 24"><path d="M5 5l14 14M19 5L5 19"/></svg>}
function Arrow(){return <span aria-hidden="true">→</span>}
function InstagramIcon(){return <svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>}
function WhatsIcon(){return <svg className="social-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .3 5.3.3 11.8c0 2.1.6 4.2 1.7 6L.2 24l6.4-1.7a11.8 11.8 0 0 0 5.5 1.4h.1c6.5 0 11.8-5.3 11.8-11.8 0-3.2-1.2-6.2-3.5-8.4Zm-8.4 18.2h-.1a9.8 9.8 0 0 1-5-1.4l-.4-.2-3.8 1 1-3.7-.2-.4a9.8 9.8 0 0 1-1.5-5.2c0-5.5 4.5-9.9 10-9.9a9.8 9.8 0 0 1 7 2.9 9.8 9.8 0 0 1 2.9 7c0 5.4-4.5 9.9-9.9 9.9Zm5.4-7.4c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-.3-.2-1.3-.5-2.5-1.6a9.4 9.4 0 0 1-1.7-2.1c-.2-.3 0-.5.1-.6l.5-.6.3-.5c.1-.2 0-.4 0-.5-.1-.2-.7-1.7-1-2.3-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1.1 1.1-1.1 2.6s1.1 3 1.3 3.2c.1.2 2.2 3.4 5.4 4.8.8.3 1.4.5 1.9.6.8.2 1.5.2 2 .1.6-.1 1.8-.7 2-1.5.3-.7.3-1.4.2-1.5 0-.2-.2-.3-.5-.4Z"/></svg>}
function Flag({code,name,className=''}){return code?<span className={`flag-wrap ${className}`} title={name}><img src={`https://flagcdn.com/w80/${code}.png`} alt={`Bandeira de ${name}`} draggable="false"/></span>:null}
function Bottle({wine}){return <div className="bottle-wrap"><div className={`bottle ${wine?.tone||'blend'}`}><div className="neck"/><div className="shoulder"/><div className="body"><div className="label"><b>{(wine?.name||'VINHO').slice(0,18)}</b><small>{(wine?.winery||'VIDEIRA').slice(0,18)}</small></div></div></div></div>}
function ProductVisual({wine}){return wine?<WineThumb wine={wine}/>:<Bottle wine={wine}/>} 
function DragSlider({children,className=''}){const ref=useRef(null);const st=useRef({down:false,x:0,left:0,drag:false});const down=e=>{if(e.pointerType!=='mouse'||e.button!==0)return;const el=ref.current;if(!el)return;st.current={down:true,x:e.clientX,left:el.scrollLeft,drag:false}};const move=e=>{const el=ref.current;if(!el||!st.current.down||e.pointerType!=='mouse')return;const dx=e.clientX-st.current.x;if(!st.current.drag&&Math.abs(dx)>8){st.current.drag=true;el.classList.add('dragging');try{el.setPointerCapture?.(e.pointerId)}catch{}}if(st.current.drag){e.preventDefault();el.scrollLeft=st.current.left-dx}};const end=e=>{const el=ref.current;if(!el)return;st.current.down=false;el.classList.remove('dragging');if(st.current.drag){try{el.releasePointerCapture?.(e.pointerId)}catch{}}};const click=e=>{if(st.current.drag){e.preventDefault();e.stopPropagation();st.current.drag=false}};return <div ref={ref} className={`horizontal-scroll drag-slider ${className}`} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onClickCapture={click}>{children}</div>}
function ProductCard({w,onAdd}){const out=w.in_stock===false;return <article className={`wine-card ${out?'out-of-stock':''}`}><Flag code={w.flag} name={w.country} className="origin-flag"/>{out&&<span className="stock-badge">Sem estoque</span>}<a className="wine-card-link" href={winePath(w)}><div className="wine-image"><ProductVisual wine={w}/></div><div className="wine-meta"><small>{w.country||'Vinho'}</small><h3>{w.name}</h3><p>{w.winery}</p><span>{w.grapeDisplay||w.type||''}</span></div></a><div className="price-line"><strong>{money(w.price)}</strong><button disabled={out} onClick={e=>{e.preventDefault();e.stopPropagation();if(!out)onAdd(w)}} aria-label={out?`${w.name} sem estoque`:`Adicionar ${w.name}`}><CartIcon/></button></div></article>}

export default function Page(){
 const [wines,setWines]=useState([]),[wineryMeta,setWineryMeta]=useState([]),[cartOpen,setCartOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState('');
 const {cart,add,updateQty,remove,count:cartCount,total}=useCart();
 useEffect(()=>{Promise.all([loadCatalog(),loadWineries()]).then(([catalog,meta])=>{setWines(catalog);setWineryMeta(meta)}).catch(console.error)},[]);
 const checkout=()=>{const lines=cart.map(p=>`• ${p.qty}x ${p.name} — ${money(Number(p.price||0)*p.qty)}`).join('\n');window.open(`https://wa.me/5545999056277?text=${encodeURIComponent(`Olá! Quero consultar estes vinhos da Videira Vinhoteca:\n\n${lines}\n\nTotal: ${money(total)}`)}`,'_blank','noopener,noreferrer')};
 const doSearch=()=>{if(!searchOpen){setSearchOpen(true);return}if(query.trim())location.href=`/loja?q=${encodeURIComponent(query.trim())}`};
 const countries=useMemo(()=>{const order=['Brasil','Argentina','Chile','França','Itália','Espanha','Portugal','África do Sul','Uruguai','Estados Unidos','Alemanha'];const map=new Map();wines.forEach(w=>{if(!w.country)return;const x=map.get(w.country)||{name:w.country,flag:w.flag,count:0};x.count++;if(!x.flag&&w.flag)x.flag=w.flag;map.set(w.country,x)});return [...map.values()].sort((a,b)=>{const ia=order.indexOf(a.name),ib=order.indexOf(b.name);return (ia<0?99:ia)-(ib<0?99:ib)||b.count-a.count}).slice(0,10)},[wines]);
 const grapes=useMemo(()=>{const counts=new Map();wines.forEach(w=>{const g=w.filterGrape;if(!g)return;counts.set(g,(counts.get(g)||0)+1)});return [...counts].sort((a,b)=>a[0]==='Blends'?1:b[0]==='Blends'?-1:a[0].localeCompare(b[0],'pt-BR')).map(([name,count])=>({name,count}))},[wines]);
 const wineries=useMemo(()=>{const logos=new Map(wineryMeta.map(x=>[x.name,x.logo_url]));const m=new Map();wines.forEach(w=>{if(!w.winery)return;const x=m.get(w.winery)||{name:w.winery,count:0,country:w.country,flag:w.flag,logo_url:logos.get(w.winery)||''};x.count++;if(!x.country&&w.country)x.country=w.country;if(!x.flag&&w.flag)x.flag=w.flag;if(!x.logo_url&&logos.get(w.winery))x.logo_url=logos.get(w.winery);m.set(w.winery,x)});return [...m.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'pt-BR')).slice(0,10)},[wines,wineryMeta]);
 const diverseByCountry=(grape,limit=10)=>{const groups=new Map();wines.filter(w=>w.filterGrape===grape).forEach(w=>{const k=w.country||'Outros';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(w)});const pools=[...groups.values()];const out=[];let i=0;while(out.length<limit&&pools.some(x=>x.length)){const pool=pools[i%pools.length];if(pool?.length)out.push(pool.shift());i++}return out};
 const featured=wines.slice(0,10), newOnes=wines.slice(-10).reverse(), malbecs=diverseByCountry('Malbec'), carmeneres=diverseByCountry('Carménère'), pinots=diverseByCountry('Pinot Noir');

 return <>
  <header className="floating-header"><div className="header-pill"><a className="header-logo" href="#inicio"><img src={HEADER_LOGO} alt="Videira Vinhoteca"/></a><nav><a className="active" href="#inicio">Início</a><a href="#vinhos">Vinhos</a><a href="#uvas">Uvas</a><a href="#bodegas">Bodegas</a><a href="#sobre">Sobre nós</a><a href="#faq">FAQ</a></nav><div className="header-actions"><div className={`header-search ${searchOpen?'open':''}`}>{searchOpen&&<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doSearch()} placeholder="Buscar vinho..."/>}<button className="icon-btn search-btn" onClick={doSearch}><SearchIcon/></button></div><button className="icon-btn cart-icon" onClick={()=>setCartOpen(true)}><CartIcon/>{cartCount>0&&<span>{cartCount}</span>}</button><a className="shop-pill" href="/loja">Loja <Arrow/></a><button className={`icon-btn mobile-menu-btn ${menuOpen?'is-open':''}`} onClick={()=>setMenuOpen(v=>!v)} aria-label={menuOpen?'Fechar menu':'Abrir menu'}>{menuOpen?<CloseIcon/>:<MenuIcon/>}</button></div></div></header>
  <main>
   <section id="inicio" className="hero-clean hero-text-only"><div className="hero-text"><p className="kicker">CURADORIA DE VINHOS</p><h1>Grandes vinhos,<br/>bons momentos.</h1><p>Uma seleção de rótulos nacionais e importados para descobrir novas histórias em cada taça.</p><a className="primary-btn" href="/loja">Ver catálogo <Arrow/></a></div></section>
   <section className="regions-strip section-shell"><div className="slider-head"><h2>Explore por país</h2><a href="/loja">Ver todos <Arrow/></a></div><DragSlider className="compact country-slider">{countries.map((c,i)=><a href={`/loja?pais=${encodeURIComponent(c.name)}`} className={`region-card region-${i+1}`} key={c.name}><div className="country-card-top"><Flag code={c.flag} name={c.name} className="country-flag"/><span className="country-count">{c.count} rótulos</span></div><div className="country-card-main"><strong>{c.name}</strong><span>Explorar seleção</span></div><span className="country-card-arrow"><Arrow/></span></a>)}</DragSlider></section>
   <section id="vinhos" className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">NOSSA SELEÇÃO</p><h2>Vinhos em destaque</h2></div><a href="/loja">Ver todos <Arrow/></a></div><DragSlider className="product-row">{featured.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>
   <section className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">CATÁLOGO 2026</p><h2>Últimos adicionados</h2></div><a href="/loja">Ver todos <Arrow/></a></div><DragSlider className="product-row">{newOnes.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>
   <section className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">UMA UVA, MUITOS ESTILOS</p><h2>Malbec</h2></div><a href="/loja?uva=Malbec">Ver todos <Arrow/></a></div><DragSlider className="product-row">{malbecs.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>{carmeneres.length>0&&<section className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">INTENSIDADE E ESPECIARIAS</p><h2>Carménère</h2></div><a href="/loja?uva=Carm%C3%A9n%C3%A8re">Ver todos <Arrow/></a></div><DragSlider className="product-row">{carmeneres.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>}{pinots.length>0&&<section className="section-shell products-section"><div className="slider-head"><div><p className="kicker dark">ELEGÂNCIA EM TAÇA</p><h2>Pinot Noir</h2></div><a href="/loja?uva=Pinot%20Noir">Ver todos <Arrow/></a></div><DragSlider className="product-row">{pinots.map(w=><ProductCard key={w.id} w={w} onAdd={add}/>)}</DragSlider></section>}
   <section id="uvas" className="section-shell"><div className="slider-head"><div><p className="kicker dark">DESCUBRA SEU ESTILO</p><h2>Por uva</h2></div><a href="/loja">Ver todas <Arrow/></a></div><DragSlider className="grape-row">{grapes.map((g,i)=><a href={`/loja?uva=${encodeURIComponent(g.name)}`} className={`grape-tile grape-${i+1}`} key={g.name}><div><strong>{g.name}</strong><span>{g.name==='Blends'?'Misturas de duas ou mais uvas':`${g.count} rótulo${g.count===1?'':'s'}`}</span></div><Arrow/></a>)}</DragSlider></section>
   <section id="bodegas" className="section-shell"><div className="slider-head"><div><p className="kicker dark">PRODUTORES</p><h2>Bodegas em destaque</h2></div><a href="/loja">Ver todas <Arrow/></a></div><DragSlider className="winery-row">{wineries.map((w,i)=><a href={`/loja?bodega=${encodeURIComponent(w.name)}`} className={`winery-card winery-${i+1}`} key={w.name}><div className="winery-logo-slot">{w.logo_url?<img src={w.logo_url} alt={`Logo ${w.name}`} loading="lazy"/>:<span>{w.name.split(' ').map(v=>v[0]).join('').slice(0,3)}</span>}</div><div className="winery-card-main"><strong>{w.name}</strong><span>{w.count} rótulos{w.country?` · ${w.country}`:''}</span></div>{w.flag&&<Flag code={w.flag} name={w.country} className="country-flag small"/>}<span className="winery-arrow"><Arrow/></span></a>)}</DragSlider></section>
   <section id="sobre" className="section-shell about-section"><div className="slider-head"><div><p className="kicker dark">VIDEIRA VINHOTECA</p><h2>Sobre nós</h2></div></div><div className="about-card"><p>Selecionamos vinhos com identidade, boa procedência e histórias que merecem ser compartilhadas. Somos de Foz do Iguaçu - PR e, atualmente, trabalhamos com vendas online e também pela Shopee. Ainda não temos loja física, mas ela está nos nossos próximos passos.</p></div></section>
   <section id="faq" className="section-shell faq-section"><div className="slider-head"><div><p className="kicker dark">DÚVIDAS FREQUENTES</p><h2>FAQ</h2></div></div><div className="faq-list"><details><summary>Como faço um pedido?</summary><p>Adicione os rótulos ao carrinho e clique em “Continuar no WhatsApp”.</p></details><details><summary>Posso filtrar os vinhos?</summary><p>Sim. Na Loja você pode pesquisar e filtrar por país, uva e bodega.</p></details><details><summary>Vocês entregam para outras cidades?</summary><p>Consulte disponibilidade, prazo e frete diretamente pelo WhatsApp.</p></details></div></section>
  </main>
  <footer><div className="footer-brand"><div className="footer-logo-lockup"><img src={HEADER_LOGO} alt="Videira Vinhoteca"/></div><p>Curadoria de vinhos com identidade.</p><span className="footer-location">Foz do Iguaçu - PR · Vendas online e Shopee</span></div><div className="footer-columns"><div><h4>Menu</h4><a href="#inicio">Início</a><a href="/loja">Loja</a><a href="#uvas">Uvas</a><a href="#bodegas">Bodegas</a></div><div><h4>Políticas</h4><a href="/politicas/privacidade">Privacidade</a><a href="/politicas/trocas">Trocas e devoluções</a><a href="/politicas/termos">Termos de uso</a></div></div><div className="footer-contact"><h4>Redes sociais</h4><div className="socials"><a href="https://instagram.com/Videiravinhoteca" target="_blank"><InstagramIcon/></a><a href="https://wa.me/5545999056277" target="_blank"><WhatsIcon/></a></div><span>@Videiravinhoteca</span></div></footer><div className="site-bottom">© 2026 Videira Vinhoteca · CNPJ 69.423.008/0001-67</div>

  <aside className={`mobile-menu ${menuOpen?'open':''}`}>
    <div className="mobile-menu-shell">
      <nav className="mobile-menu-links"><a href="#inicio" onClick={()=>setMenuOpen(false)}>Início</a><a href="/loja">Loja</a><a href="#vinhos" onClick={()=>setMenuOpen(false)}>Vinhos</a><a href="#uvas" onClick={()=>setMenuOpen(false)}>Uvas</a><a href="#bodegas" onClick={()=>setMenuOpen(false)}>Bodegas</a><a href="#sobre" onClick={()=>setMenuOpen(false)}>Sobre nós</a><a href="#faq" onClick={()=>setMenuOpen(false)}>FAQ</a></nav>
    </div>
  </aside>{menuOpen&&<button className="menu-backdrop" onClick={()=>setMenuOpen(false)}/>}
  <a className="whatsapp-float" href="https://wa.me/5545999056277" target="_blank"><WhatsIcon/></a>
  <aside className={`cart-drawer ${cartOpen?'open':''}`}><button className="drawer-close" onClick={()=>setCartOpen(false)}>×</button><p className="kicker dark">SEU CARRINHO</p><h2>Minha seleção</h2><div className="cart-items">{cart.length===0?<p className="empty">Seu carrinho está vazio.</p>:cart.map(p=><div className="cart-item" key={p.id}><div><strong>{p.name}</strong><span>{p.winery}</span><div className="cart-qty"><button onClick={()=>updateQty(p.id,p.qty-1)}>−</button><input type="number" min="1" value={p.qty} onChange={e=>updateQty(p.id,e.target.value)}/><button onClick={()=>updateQty(p.id,p.qty+1)}>+</button></div></div><div><b>{money(Number(p.price||0)*p.qty)}</b><button onClick={()=>remove(p.id)}>Remover</button></div></div>)}</div><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="checkout" disabled={!cart.length} onClick={checkout}>Continuar no WhatsApp</button></aside>{cartOpen&&<button className="backdrop" onClick={()=>setCartOpen(false)}/>}
 </>;
}
